# Generated by Django 4.2 on 2023-04-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ASL', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='user',
            new_name='creator',
        ),
    ]
