# Generated by Django 4.2 on 2023-04-03 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ASL', '0003_chatbox_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbox',
            name='all_messages',
        ),
    ]
