# Generated by Django 4.2 on 2023-04-03 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ASL', '0005_remove_messages_creator_messages_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbox',
            name='users',
        ),
    ]
