# Generated by Django 4.2 on 2023-04-03 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ASL', '0006_remove_chatbox_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbox',
            name='users',
            field=models.ManyToManyField(related_name='chat_box_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatbox',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_box_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
