# Generated by Django 4.2 on 2023-04-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASL', '0007_chatbox_users_alter_chatbox_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbox',
            name='messages',
            field=models.ManyToManyField(related_name='chat_box_messages', to='ASL.messages'),
        ),
    ]
