# Generated by Django 4.2 on 2023-04-03 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ASL', '0008_chatbox_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbox',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='chatbox',
            name='users',
        ),
    ]
