# Generated by Django 4.1.7 on 2023-04-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_remove_conversation_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='category',
            field=models.CharField(default='', max_length=128),
        ),
    ]
